### PR TITLE
Update elife/reference-schematron to aec5aa8

### PR DESCRIPTION
**Pull request by giorgiosironi**
See https://github.com/elifesciences/reference-schematron/pull/6#issuecomment-371164449

### CODE REVIEW

**Comment by giorgiosironi** [comment]
A test failed:
```
[52.91.22.130] out: 1) ValidatorTest::testFiles with data set #86 ('/srv/schematron-validator/tes...al.xml')
[52.91.22.130] out: pass-High-6-ref-element-citation-clinical-trial.xml should pass on final, but didn't: [err-elem-cit-high-6-2]
[52.91.22.130] out:         The publication-type attribute may only take the values 'journal', 'book', 'data', 
[52.91.22.130] out:         'patent', 'software', 'preprint', 'web', 
[52.91.22.130] out:         'periodical', 'report', 'confproc', or 'thesis'. 
[52.91.22.130] out:         Reference '' has the publication-type 
[52.91.22.130] out:         ''.
[52.91.22.130] out: Failed asserting that two strings are equal.
[52.91.22.130] out: --- Expected
[52.91.22.130] out: +++ Actual
[52.91.22.130] out: @@ @@
[52.91.22.130] out: -'VALID'
[52.91.22.130] out: +'INVALID'
```
Does that make any sense to you @JGilbert-eLife?

**Comment by JGilbert-eLife** [comment]
Yes, it does. The clinical trial test files are still there. Apologies, I'd overlooked that. I'll have to dig through the test files and some of the checks will need to be removed or updated.

**Comment by JGilbert-eLife** [comment]
We need to remove the test files:

fail-High-6-ref-element-citation-clinical-trial-alt.xml
fail-High-6-ref-element-citation-clinical-trial.xml
pass-High-6-ref-element-citation-clinical-trial.xml

There are presumably three tests that correspond to these that will need to be removed as well.

**Comment by JGilbert-eLife** [comment]
I'm not sure if anything needs to be changed in the validator now that I have removed the clinical-trial test files. Do you know if changes are required @giorgiosironi ?

**Comment by giorgiosironi** [comment]
I'll rebuild this with the latest `reference-schematron`.

**Comment by giorgiosironi** [comment]
Now green again. I'll merge and bring it live in production.

**Comment by JGilbert-eLife** [comment]
Great, thanks Giorgio.

**Pull request merged**
